kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-{{ .Release.Name }}-route
spec:
  to:
    kind: Service
    name: el-{{ .Release.Name }}-event-listener
  port:
    targetPort: 8080
